name          'puppet-varnish'
version       '0.0.1'
source        'UNKNOWN'
author        'Facundo Guerrero'
license       'Apache License, Version 2.0'
summary       'This module installs and manages varnish'
description   'This module installs and manages varnish'
project_page  'github.com/guerrermdq/puppet-varnish'
dependency    'puppetlabs/stdlib'
